{"version":3,"sources":["scripts/main.js"],"names":["logo","document","querySelector","callbackPromise","isResolved","Promise","resolve","reject","Error","promise1","promise2","showText","text","divClass","divTag","createElement","textContent","className","body","appendChild","callbackSuccess","success","addEventListener","callbackError","err","setTimeout","then","catch","error"],"mappings":";AAAA,aAGA,IAAMA,EAAOC,SAASC,cAAc,SAE9BC,EAAkB,SAAAC,GACf,OAAA,IAAIC,QAAQ,SAACC,EAASC,GACpBH,OAAAA,EACHE,EAAQ,yBACRC,EAAO,IAAIC,MAAM,4BAInBC,EAAW,WAAMN,OAAAA,GAAgB,IAEjCO,EAAW,WAAMP,OAAAA,GAAgB,IAEjCQ,EAAW,SAACC,EAAMC,GAChBC,IAAAA,EAASb,SAASc,cAAc,OAEtCD,EAAOE,YAAcJ,EAErBE,EAAOG,UAAYJ,EAEnBZ,SAASiB,KAAKC,YAAYL,IAGtBM,EAAkB,SAAAC,GACtBrB,EAAKsB,iBAAiB,QAAS,WAC7BX,EAASU,EAAS,cAIhBE,EAAgB,SAAAC,GACpBxB,EAAKsB,iBAAiB,QAAS,WAC7BG,WAAW,WACTd,EAASa,EAAK,kBACb,QAIPf,IACGiB,KAAK,SAAAL,GAAWD,OAAAA,EAAgBC,KAChCM,MAAM,SAAAC,GAASL,OAAAA,EAAcK,KAEhClB,IACGgB,KAAK,SAAAL,GAAWD,OAAAA,EAAgBC,KAChCM,MAAM,SAAAC,GAASL,OAAAA,EAAcK","file":"main.1429f97d.js","sourceRoot":"..\\src","sourcesContent":["'use strict';\n\n// write your code here\nconst logo = document.querySelector('.logo');\n\nconst callbackPromise = isResolved => {\n  return new Promise((resolve, reject) => {\n    return isResolved\n      ? resolve('Promise was resolved!')\n      : reject(new Error('Promise was rejected'));\n  });\n};\n\nconst promise1 = () => callbackPromise(true);\n\nconst promise2 = () => callbackPromise(false);\n\nconst showText = (text, divClass) => {\n  const divTag = document.createElement('div');\n\n  divTag.textContent = text;\n\n  divTag.className = divClass;\n\n  document.body.appendChild(divTag);\n};\n\nconst callbackSuccess = success => {\n  logo.addEventListener('click', () => {\n    showText(success, 'message');\n  });\n};\n\nconst callbackError = err => {\n  logo.addEventListener('click', () => {\n    setTimeout(() => {\n      showText(err, 'error-message');\n    }, 3000);\n  });\n};\n\npromise1()\n  .then(success => callbackSuccess(success))\n  .catch(error => callbackError(error));\n\npromise2()\n  .then(success => callbackSuccess(success))\n  .catch(error => callbackError(error));\n"]}